# Generated by Django 6.0.6 on 2026-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentes',
            name='activo',
        ),
        migrations.AddField(
            model_name='agentes',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentes',
            name='temperatura',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='agentes',
            name='tokens',
            field=models.IntegerField(default=1000),
        ),
    ]
