# Generated by Django 6.0.6 on 2026-07-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_remove_agentes_activo_agentes_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CausaRaiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=200)),
                ('accion_correctiva', models.TextField()),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentes.falla')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
                ('orden', models.IntegerField(default=1)),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentes.falla')),
            ],
        ),
    ]
