# Generated by Django 5.2.15 on 2026-07-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_falla_causaraiz_preguntadiagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='causaraiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='falla',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preguntadiagnostico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
