# Generated by Django 5.2.16 on 2026-07-10 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0006_agentechatmensaje_seed_agentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentes',
            name='es_base',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AgenteEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('created_manual', 'Creado manual'), ('created_generated', 'Creado generado'), ('created_base', 'Creado base'), ('edited', 'Editado'), ('deleted', 'Eliminado'), ('chat_used', 'Usado en chat')], max_length=30)),
                ('agente_nombre', models.CharField(blank=True, max_length=120)),
                ('agente_es_base', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.agentes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
