# Generated by Django 5.2.16 on 2026-08-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0009_causaraiz_disparadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaraiz',
            name='respuesta_disparadora',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
    ]
