# Generated by Django 6.0.6 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0011_arbol_decision_ramificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaraiz',
            name='recomendacion_seguridad',
            field=models.TextField(blank=True, default='', help_text='Recomendación de seguridad (LOTO) para esta acción correctiva, si aplica.'),
        ),
    ]
