# Generated by Django 6.0.6 on 2026-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostico',
            field=models.TextField(),
        ),
    ]
