# Generated by Django 5.2.16 on 2026-07-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('VISITANTE', 'Visitante'), ('ADMIN', 'Administrador'), ('DESARROLLADOR', 'Desarrollador')], default='VISITANTE', max_length=20),
        ),
    ]
