# Generated by Django 6.0.6 on 2026-08-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_seed_usuarios_readme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
    ]
